export const maincategories = [
  {
    id: 1,
    image: require("./assets/images/Top.png"),
    title: "Tops",
    description: "This is a description for category 1.",
  },
  {
    id: 2,
    image: require("./assets/images/Bottom.png"),
    title: "Bottoms",
    description: "This is a description for category 2.",
  },
  {
    id: 4,
    image: require("./assets/images/Outwear.png"),
    title: "Outerwear",
    description: "This is a description for category 4.",
  },
  {
    id: 5,
    image: require("./assets/images/Activewear.png"),
    title: "Activewear",
    description: "This is a description for category 5.",
  },
  {
    id: 6,
    image: require("./assets/images/Sleepwear.png"),
    title: "Sleepwear",
    description: "This is a description for category 6.",
  },
  {
    id: 7,
    image: "https://via.placeholder.com/250",
    title: "Underwear",
    description: "This is a description for category 7.",
  },
  {
    id: 8,
    image: require("./assets/images/Accessories.png"),
    title: "Accessories",
    description: "This is a description for category 8.",
  },
  {
    id: 9,
    image: "https://via.placeholder.com/250",
    title: "Footwear",
    description: "This is a description for category 9.",
  },
];

export const subcategories = [
  {
    mainCategoryId: 1,
    subcategories: [
      { title: "T-shirts", image: "https://via.placeholder.com/150" },
      { title: "Shirts", image: "https://via.placeholder.com/150" },
      { title: "Blouses", image: "https://via.placeholder.com/150" },
      { title: "Sweaters", image: "https://via.placeholder.com/150" },
      { title: "Hoodies", image: "https://via.placeholder.com/150" },
    ],
  },
  {
    mainCategoryId: 2,
    subcategories: [
      { title: "Jeans", image: "https://via.placeholder.com/150" },
      { title: "Trousers", image: "https://via.placeholder.com/150" },
      { title: "Skirts", image: "https://via.placeholder.com/150" },
      { title: "Shorts", image: "https://via.placeholder.com/150" },
      { title: "Leggings", image: "https://via.placeholder.com/150" },
    ],
  },
  {
    mainCategoryId: 3,
    subcategories: [
      { title: "Casual Dresses", image: "https://via.placeholder.com/150" },
      { title: "Formal Dresses", image: "https://via.placeholder.com/150" },
      { title: "Party Dresses", image: "https://via.placeholder.com/150" },
      { title: "Maxi Dresses", image: "https://via.placeholder.com/150" },
      { title: "Midi Dresses", image: "https://via.placeholder.com/150" },
    ],
  },
  {
    mainCategoryId: 4,
    subcategories: [
      { title: "Jackets", image: "https://via.placeholder.com/150" },
      { title: "Coats", image: "https://via.placeholder.com/150" },
      { title: "Blazers", image: "https://via.placeholder.com/150" },
      { title: "Cardigans", image: "https://via.placeholder.com/150" },
      { title: "Vests", image: "https://via.placeholder.com/150" },
    ],
  },
  {
    mainCategoryId: 5,
    subcategories: [
      { title: "Sports Bras", image: "https://via.placeholder.com/150" },
      { title: "Leggings", image: "https://via.placeholder.com/150" },
      { title: "Athletic Shorts", image: "https://via.placeholder.com/150" },
      { title: "Sweatpants", image: "https://via.placeholder.com/150" },
      { title: "Active Tops", image: "https://via.placeholder.com/150" },
    ],
  },
  {
    mainCategoryId: 6,
    subcategories: [
      { title: "Pajamas", image: "https://via.placeholder.com/150" },
      { title: "Nightgowns", image: "https://via.placeholder.com/150" },
      { title: "Robes", image: "https://via.placeholder.com/150" },
      { title: "Loungewear", image: "https://via.placeholder.com/150" },
    ],
  },
  {
    mainCategoryId: 7,
    subcategories: [
      { title: "Bras", image: "https://via.placeholder.com/150" },
      { title: "Panties", image: "https://via.placeholder.com/150" },
      { title: "Boxers", image: "https://via.placeholder.com/150" },
      { title: "Briefs", image: "https://via.placeholder.com/150" },
    ],
  },
  {
    mainCategoryId: 8,
    subcategories: [
      { title: "Hats", image: "https://via.placeholder.com/150" },
      { title: "Scarves", image: "https://via.placeholder.com/150" },
      { title: "Gloves", image: "https://via.placeholder.com/150" },
      { title: "Belts", image: "https://via.placeholder.com/150" },
      { title: "Socks", image: "https://via.placeholder.com/150" },
    ],
  },
  {
    mainCategoryId: 9,
    subcategories: [
      { title: "Sneakers", image: "https://via.placeholder.com/150" },
      { title: "Boots", image: "https://via.placeholder.com/150" },
      { title: "Sandals", image: "https://via.placeholder.com/150" },
      { title: "Flats", image: "https://via.placeholder.com/150" },
      { title: "Heels", image: "https://via.placeholder.com/150" },
    ],
  },
];

export const clothes = [
  {
    name: "Cotton T-shirt",
    id: 1,
    subCategory: "T-shirts",
    price: 19.99,
    image: require("./assets/images/CottonTshirt.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Cotton T-shirt",
    id: 1,
    subCategory: "T-shirts",
    price: 19.99,
    image: require("./assets/images/CottonTshirt.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Slim Fit Jeans",
    id: 2,
    subCategory: "Jeans",
    price: 49.99,
    image: require("./assets/images/SlimFitJeans.webp"),
    description: "This is a good item , this is a good item",
  },

  {
    name: "Leather Jacket",
    id: 4,
    subCategory: "Jackets",
    price: 129.99,
    image: require("./assets/images/LeatherJacket.webp"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Running Shorts",
    id: 5,
    subCategory: "Athletic Shorts",
    price: 29.99,
    image: require("./assets/images/RunningShorts.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Silk Pajamas",
    id: 6,
    subCategory: "Pajamas",
    price: 59.99,
    image: require("./assets/images/SilkPajamas.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Lace Bra",
    id: 7,
    subCategory: "Bras",
    price: 24.99,
    image: "https://via.placeholder.com/250",
    description: "This is a good item , this is a good item",
  },
  {
    name: "Knit Beanie",
    id: 8,
    subCategory: "Hats",
    price: 14.99,
    image: require("./assets/images/KnitBeanie.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Canvas Sneakers",
    id: 9,
    subCategory: "Sneakers",
    price: 39.99,
    image: require("./assets/images/Canvas Sneakers.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "V-neck Sweater",
    id: 1,
    subCategory: "Sweaters",
    price: 49.99,
    image: require("./assets/images/VneckSweater.webp"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Cargo Pants",
    id: 2,
    subCategory: "Trousers",
    price: 59.99,
    image: require("./assets/images/CargoPants.webp"),
    description: "This is a good item , this is a good item",
  },

  {
    name: "Raincoat",
    id: 4,
    subCategory: "Coats",
    price: 99.99,
    image: require("./assets/images/Raincoatjpg.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Yoga Leggings",
    id: 5,
    subCategory: "Leggings",
    price: 34.99,
    image: require("./assets/images/YogaLeggings.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Flannel Pajama Set",
    id: 6,
    subCategory: "Loungewear",
    price: 69.99,
    image: require("./assets/images/FlannelPajamaSetavif.avif"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Boxer Briefs (3-pack)",
    id: 7,
    subCategory: "Boxers",
    price: 19.99,
    image: "https://via.placeholder.com/250",
    description: "This is a good item , this is a good item",
  },
  {
    name: "Leather Belt",
    id: 8,
    subCategory: "Belts",
    price: 29.99,
    image: require("./assets/images/LeatherBelt.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Ankle Boots",
    id: 9,
    subCategory: "Boots",
    price: 79.99,
    image: require("./assets/images/Ankle Bootsjpg.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Graphic Tee",
    id: 1,
    subCategory: "T-shirts",
    price: 24.99,
    image: require("./assets/images/GraphicTee.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Wide-Leg Pants",
    id: 2,
    subCategory: "Trousers",
    price: 69.99,
    image: require("./assets/images/WideLegPants.jpg"),
    description: "This is a good item , this is a good item",
  },

  {
    name: "Quilted Jacket",
    id: 4,
    subCategory: "Jackets",
    price: 149.99,
    image: require("./assets/images/QuiltedJacket.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Track Pants",
    id: 5,
    subCategory: "Sweatpants",
    price: 44.99,
    image: require("./assets/images/TrackPants.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Silk Robe",
    id: 6,
    subCategory: "Robes",
    price: 99.99,
    image: require("./assets/images/SilkRobe.jpg"),
    description: "This is a good item , this is a good item",
  },

  {
    name: "Wool Fedora",
    id: 8,
    subCategory: "Hats",
    price: 34.99,
    image: require("./assets/images/Wool Fedorajpg.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Classic Loafers",
    id: 9,
    subCategory: "Flats",
    price: 59.99,
    image: "https://via.placeholder.com/250",
    description: "This is a good item , this is a good item",
  },
  {
    name: "Striped Polo",
    id: 1,
    subCategory: "Shirts",
    price: 29.99,
    image: require("./assets/images/StripedPolo.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Cargo Shorts",
    id: 2,
    subCategory: "Shorts",
    price: 34.99,
    image: require("./assets/images/CargoShorts.jpg"),
    description: "This is a good item , this is a good item",
  },

  {
    name: "Peacoat",
    id: 4,
    subCategory: "Coats",
    price: 179.99,
    image: require("./assets/images/Peacoat.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Hooded Sweatshirt",
    id: 5,
    subCategory: "Hoodies",
    price: 54.99,
    image: require("./assets/images/HoodedSweatshirt.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Silk Nightgown",
    id: 6,
    subCategory: "Nightgowns",
    price: 79.99,
    image: require("./assets/images/SilkNightgown.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "Sports Bra",
    id: 7,
    subCategory: "Sports Bras",
    price: 34.99,
    image: "https://via.placeholder.com/250",
    description: "This is a good item , this is a good item",
  },
  {
    name: "Leather Gloves",
    id: 8,
    subCategory: "Gloves",
    price: 39.99,
    image: require("./assets/images/Leather Glovesjpg.jpg"),
    description: "This is a good item , this is a good item",
  },
  {
    name: "High Heels",
    id: 9,
    subCategory: "Heels",
    price: 89.99,
    image: "https://via.placeholder.com/250",
    description: "This is a good item , this is a good item",
  },
];
